import makeWASocket, { useMultiFileAuthState, DisconnectReason } from '@whiskeysockets/baileys';
import pino from 'pino';
import qrcode from 'qrcode-terminal'; // 1. Import this helper

let sock = null;

export async function connectToWhatsApp() {
    const { state, saveCreds } = await useMultiFileAuthState('auth_info');

    sock = makeWASocket({
        auth: state,
        logger: pino({ level: 'error' })
    });

    // 2. FORCE the QR code to print directly to the console manually
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect, qr } = update;
        
        // If a QR code is generated by WhatsApp's servers, intercept and print it
        if (qr) {
            console.log('🔽 SCAN THIS QR CODE WITH WHATSAPP 🔽\n');
            qrcode.generate(qr, { small: true });
        }

        if (connection === 'close') {
            const shouldReconnect = lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut;
            console.log('🔄 Reconnecting to WhatsApp gateway...');
            if (shouldReconnect) connectToWhatsApp();
        } else if (connection === 'open') {
            console.log('✅ Success: WhatsApp OTP Gateway client linked successfully!');
        }
    });

    sock.ev.on('creds.update', saveCreds);
}

export const getWhatsAppSocket = () => sock;